/**
 * Glass Lab style presets.
 * Every preset feeds the LiquidGlass component ported from
 * Kyant0/AndroidLiquidGlass (Apache-2.0).
 *
 * Phase 2: the library doubled to 24 curated styles, organized into four
 * categories (经典 / 材质 / 光影 / 创意), with a new `lightAngle` engine
 * parameter controlling the direction of the fresnel rim highlight.
 */

export interface GlassConfig {
  /** Rim refraction strength — max displacement in px (Kyant0: refractionAmount) */
  refraction: number
  /** Refracting rim thickness in px (Kyant0: refractionHeight) */
  height: number
  /** Spectral dispersion / chromatic aberration, 0..1 */
  dispersion: number
  /** Extra gaussian blur of the backdrop in px */
  blur: number
  /** Backdrop saturation, % */
  saturation: number
  /** Corner radius in px; use 999 for a pill shape */
  cornerRadius: number
  /** Radial depth pull (Kyant0: depthEffect) */
  depthEffect: boolean
  /** Fresnel rim highlight intensity, 0..1 */
  highlight: number
  /** Fresnel rim highlight direction, degrees (0 = to top, clockwise) */
  lightAngle: number
  /** Phase 8: fresnel rim highlight color (#hex / rgb() / hsl()) */
  highlightColor: string
  /** Tint color applied over the glass */
  tint: string
  /** Tint opacity, 0..1 */
  tintOpacity: number
  /** Dark glass mode for bright backgrounds */
  overLight: boolean
  /** Drag elasticity of the demo card, 0..1 */
  elasticity: number
  /** Optional colored glow outside the glass */
  glow: string
  /** Phase 9 M1: glow intensity multiplier — final alpha = glow's own alpha × this, 0..1 */
  glowOpacity: number
  /** Phase 9 M1: glow diffusion radius in px (box-shadow blur radius) */
  glowSpread: number
  /** Phase 9 M3: glow breathing speed — 0=off, 1=fastest (period 3.6s→0.6s) */
  glowPulse: number
  /** Phase 9 M3: rim highlight flow speed — 0=off, 1=fastest (period 6s→1.5s) */
  rimFlow: number
  /** Phase 5: frosted grain overlay (SVG feTurbulence noise), 0..1 */
  frost: number
  /** Phase 9 M2: horizontal brushed-metal streaks, 0..1 */
  brushed: number
  /** Phase 10 M1: brushed streak direction in degrees (0 = horizontal) */
  brushedAngle: number
  /** Phase 9 M2: gas-bubble texture overlay, 0..1 */
  bubbles: number
  /** Phase 10 M2: bubble radius scale (default 1 = Phase 9 layout) */
  bubbleSize: number
  /** Phase 10 M2: bubble count scale (default 1 = 8 bubbles per tile) */
  bubbleDensity: number
  /** Phase 10 M2: bubble rise speed — 0=off, 1=fastest (period 8s→1.5s) */
  bubbleRise: number
  /** Phase 11 M1: directional cast shadow intensity, 0..1 (0 = off) */
  shadowIntensity: number
  /** Phase 11 M1: cast shadow offset distance in px */
  shadowDistance: number
  /** Phase 11 M1: cast shadow feather radius in px */
  shadowSoftness: number
  /** Phase 11 M2: pointer becomes the light source (stage interactive) */
  lightFollow: boolean
  /** Phase 11 M2: brushed streaks stay perpendicular to the light */
  brushedFollow: boolean
  /** Phase 5: progressive gaussian blur ring at the glass edges, 0..1 */
  edgeBlur: number
  /** Phase 5: radial corner darkening (vignette), 0..1 */
  vignette: number
}

export type GlassCategory = '经典' | '材质' | '光影' | '创意'

export const CATEGORIES: readonly GlassCategory[] = ['经典', '材质', '光影', '创意']

/** Cross-cutting filter value for the category chips (Phase 11 M3). */
export type CategoryFilter = '全部' | GlassCategory | '动效'

/**
 * Phase 11 M3: a preset carries motion when any animation parameter is on
 * (glow breathing / rim flow / bubble rise). Used for the「动效」badge and
 * the cross-category filter chip.
 */
export function isMotionConfig(c: GlassConfig): boolean {
  return (
    (c.glowPulse ?? 0) > 0.01 || (c.rimFlow ?? 0) > 0.01 || (c.bubbleRise ?? 0) > 0.01
  )
}

export interface GlassPreset {
  id: string
  name: string
  /** Small hint shown under the name */
  desc: string
  /** css gradient used for the preset thumbnail */
  swatch: string
  category: GlassCategory
  config: GlassConfig
}

export const DEFAULT_CONFIG: GlassConfig = {
  refraction: 28,
  height: 42,
  dispersion: 0.35,
  blur: 2,
  saturation: 120,
  cornerRadius: 26,
  depthEffect: false,
  highlight: 0.85,
  lightAngle: 45,
  highlightColor: '#ffffff',
  tint: '#ffffff',
  tintOpacity: 0.08,
  overLight: false,
  elasticity: 0.55,
  glow: 'transparent',
  glowOpacity: 1,
  glowSpread: 24,
  glowPulse: 0,
  rimFlow: 0,
  frost: 0,
  brushed: 0,
  brushedAngle: 0,
  bubbles: 0,
  bubbleSize: 1,
  bubbleDensity: 1,
  bubbleRise: 0,
  shadowIntensity: 0,
  shadowDistance: 14,
  shadowSoftness: 28,
  lightFollow: false,
  brushedFollow: false,
  edgeBlur: 0,
  vignette: 0,
}

export const PRESETS: GlassPreset[] = [
  // ------------------------------ 经典 ------------------------------
  {
    id: 'ios-clear',
    name: 'iOS 经典',
    desc: 'Apple 官方透明液态玻璃',
    swatch: 'linear-gradient(135deg,#7dd3fc,#c4b5fd,#fda4af)',
    category: '经典',
    config: { ...DEFAULT_CONFIG },
  },
  {
    id: 'pill-dock',
    name: '灵动胶囊',
    desc: 'Dynamic Island 药丸形',
    swatch: 'linear-gradient(90deg,#111,#333,#111)',
    category: '经典',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 34,
      height: 46,
      dispersion: 0.3,
      blur: 2,
      saturation: 130,
      cornerRadius: 999,
      tint: '#000000',
      tintOpacity: 0.2,
      highlight: 0.95,
      glow: 'rgba(255,255,255,0.12)',
    },
  },
  {
    id: 'thin-lens',
    name: '超薄玻璃',
    desc: '轻薄贴合，边缘微折射',
    swatch: 'linear-gradient(135deg,#f8fafc,#e2e8f0,#f1f5f9)',
    category: '经典',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 16,
      height: 20,
      dispersion: 0.25,
      blur: 1,
      saturation: 115,
      cornerRadius: 18,
      highlight: 0.8,
      tintOpacity: 0.05,
      lightAngle: 60,
    },
  },
  {
    id: 'vision-panel',
    name: 'visionOS 面板',
    desc: '空间系统深色面板',
    swatch: 'linear-gradient(135deg,#1e293b,#0f172a,#334155)',
    category: '经典',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 24,
      height: 40,
      dispersion: 0.3,
      blur: 12,
      saturation: 140,
      cornerRadius: 28,
      tint: '#0f172a',
      tintOpacity: 0.28,
      highlight: 0.7,
      lightAngle: 135,
    },
  },
  {
    id: 'liquid-bar',
    name: '液态通知条',
    desc: '灵动通知，柔雾悬浮',
    swatch: 'linear-gradient(135deg,#0f172a,#334155,#0f172a)',
    category: '经典',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 36,
      height: 50,
      dispersion: 0.4,
      blur: 4,
      saturation: 140,
      cornerRadius: 999,
      tint: '#0f172a',
      tintOpacity: 0.24,
      highlight: 0.9,
      frost: 0.2,
      glow: 'rgba(255,255,255,0.1)',
    },
  },
  {
    id: 'obsidian-panel',
    name: '黑曜面板',
    desc: '专业深色工作台',
    swatch: 'linear-gradient(150deg,#292524,#0c0a09,#44403c)',
    category: '经典',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 26,
      height: 42,
      dispersion: 0.28,
      blur: 5,
      saturation: 105,
      cornerRadius: 20,
      tint: '#0c0a09',
      tintOpacity: 0.5,
      highlight: 0.9,
      vignette: 0.3,
      lightAngle: 160,
    },
  },
  {
    id: 'gold-rim',
    name: '鎏金辉光',
    desc: '金色高光，暖调奢华',
    swatch: 'linear-gradient(135deg,#fde68a,#f59e0b,#78350f)',
    category: '经典',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 26,
      height: 42,
      dispersion: 0.35,
      blur: 4,
      saturation: 135,
      cornerRadius: 24,
      tint: '#78350f',
      tintOpacity: 0.2,
      highlight: 1,
      highlightColor: '#fbbf24',
      lightAngle: 315,
      glow: 'rgba(251,191,36,0.3)',
    },
  },

  // ------------------------------ 材质 ------------------------------
  {
    id: 'frosted',
    name: '磨砂玻璃',
    desc: '重雾面，隐私友好',
    swatch: 'linear-gradient(135deg,#e2e8f0,#cbd5e1,#94a3b8)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 10,
      height: 26,
      dispersion: 0.1,
      blur: 14,
      saturation: 140,
      cornerRadius: 30,
      tintOpacity: 0.16,
      highlight: 0.6,
    },
  },
  {
    id: 'ice',
    name: '冰川玻璃',
    desc: '清透冰蓝，冷静纯净',
    swatch: 'linear-gradient(135deg,#bae6fd,#e0f2fe,#f8fafc)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 14,
      height: 30,
      dispersion: 0.2,
      blur: 18,
      saturation: 70,
      cornerRadius: 32,
      tint: '#bae6fd',
      tintOpacity: 0.2,
      highlight: 0.75,
    },
  },
  {
    id: 'smoked',
    name: '烟熏玻璃',
    desc: '深色低调商务风',
    swatch: 'linear-gradient(135deg,#334155,#1e293b,#0f172a)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 20,
      height: 32,
      dispersion: 0.15,
      blur: 8,
      saturation: 90,
      cornerRadius: 24,
      tint: '#0f172a',
      tintOpacity: 0.42,
      highlight: 0.5,
    },
  },
  {
    id: 'obsidian',
    name: '黑曜石',
    desc: '深邃黑曜，锋利高光',
    swatch: 'linear-gradient(135deg,#0c0a09,#1c1917,#292524)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 24,
      height: 36,
      dispersion: 0.22,
      blur: 5,
      saturation: 80,
      cornerRadius: 18,
      tint: '#0c0a09',
      tintOpacity: 0.58,
      highlight: 1,
      glow: 'rgba(255,255,255,0.08)',
    },
  },
  {
    id: 'jade',
    name: '玉石玻璃',
    desc: '温润玉色，东方质感',
    swatch: 'linear-gradient(135deg,#6ee7b7,#10b981,#047857)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 22,
      height: 38,
      dispersion: 0.2,
      blur: 10,
      saturation: 130,
      cornerRadius: 26,
      tint: '#10b981',
      tintOpacity: 0.3,
      highlight: 0.7,
      lightAngle: 90,
    },
  },
  {
    id: 'velvet',
    name: '丝绒雾面',
    desc: '深紫丝绒，柔雾哑光',
    swatch: 'linear-gradient(135deg,#7c3aed,#4c1d95,#2e1065)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 12,
      height: 26,
      dispersion: 0.1,
      blur: 20,
      saturation: 90,
      cornerRadius: 30,
      tint: '#4c1d95',
      tintOpacity: 0.4,
      highlight: 0.4,
      lightAngle: 200,
    },
  },
  {
    id: 'mocha',
    name: '摩卡奶油',
    desc: '咖啡奶泡，暖棕柔和',
    swatch: 'linear-gradient(135deg,#d6bfa2,#92400e,#5c3317)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 14,
      height: 30,
      dispersion: 0.15,
      blur: 16,
      saturation: 110,
      cornerRadius: 32,
      tint: '#92400e',
      tintOpacity: 0.26,
      highlight: 0.6,
    },
  },
  {
    id: 'etched',
    name: '磨砂蚀刻',
    desc: '噪点磨砂，颗粒质感',
    swatch: 'linear-gradient(135deg,#e7e5e4,#d6d3d1,#a8a29e)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 12,
      height: 28,
      dispersion: 0.08,
      blur: 16,
      saturation: 105,
      cornerRadius: 30,
      tintOpacity: 0.18,
      highlight: 0.55,
      frost: 0.55,
      vignette: 0.25,
    },
  },
  {
    id: 'rose-quartz',
    name: '蔷薇石英',
    desc: '粉晶透光，温柔包裹',
    swatch: 'linear-gradient(135deg,#fbcfe8,#f9a8d4,#f472b6)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 20,
      height: 34,
      dispersion: 0.18,
      blur: 14,
      saturation: 118,
      cornerRadius: 32,
      tint: '#f9a8d4',
      tintOpacity: 0.26,
      highlight: 0.7,
      frost: 0.35,
      lightAngle: 60,
    },
  },
  {
    id: 'deep-sea',
    name: '深海之窗',
    desc: '幽蓝深处，边缘消散',
    swatch: 'linear-gradient(160deg,#082f49,#0c4a6e,#155e75)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 22,
      height: 36,
      dispersion: 0.22,
      blur: 8,
      saturation: 128,
      cornerRadius: 24,
      tint: '#0c4a6e',
      tintOpacity: 0.34,
      highlight: 0.65,
      edgeBlur: 0.5,
      vignette: 0.4,
      lightAngle: 200,
    },
  },
  {
    id: 'aurora-edge',
    name: '极光边缘',
    desc: '青碧高光，冷冽通透',
    swatch: 'linear-gradient(135deg,#ccfbf1,#5eead4,#0f766e)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 24,
      height: 40,
      dispersion: 0.3,
      blur: 9,
      saturation: 150,
      cornerRadius: 28,
      tint: '#134e4a',
      tintOpacity: 0.18,
      highlight: 1,
      highlightColor: '#5eead4',
      frost: 0.2,
      edgeBlur: 0.3,
      lightAngle: 45,
    },
  },

  // ------------------------------ 光影 ------------------------------
  {
    id: 'crystal',
    name: '水晶棱镜',
    desc: '强色散，彩虹边缘',
    swatch: 'linear-gradient(135deg,#f0abfc,#a5f3fc,#fde68a)',
    category: '光影',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 42,
      height: 62,
      dispersion: 0.85,
      blur: 0,
      saturation: 165,
      cornerRadius: 20,
      highlight: 1,
    },
  },
  {
    id: 'prism',
    name: '光学棱镜',
    desc: '极限折射 + 深度形变',
    swatch: 'conic-gradient(#f87171,#fbbf24,#4ade80,#22d3ee,#a78bfa,#f87171)',
    category: '光影',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 55,
      height: 72,
      dispersion: 1,
      blur: 0,
      saturation: 200,
      cornerRadius: 16,
      depthEffect: true,
      highlight: 1,
    },
  },
  {
    id: 'aurora',
    name: '极光玻璃',
    desc: '青绿色冷调极光',
    swatch: 'linear-gradient(135deg,#5eead4,#34d399,#a7f3d0)',
    category: '光影',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 30,
      height: 46,
      dispersion: 0.5,
      blur: 6,
      saturation: 150,
      cornerRadius: 26,
      tint: '#34d399',
      tintOpacity: 0.14,
    },
  },
  {
    id: 'amber',
    name: '琥珀玻璃',
    desc: '暖调琥珀，复古质感',
    swatch: 'linear-gradient(135deg,#fbbf24,#f59e0b,#b45309)',
    category: '光影',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 26,
      height: 40,
      dispersion: 0.4,
      blur: 3,
      saturation: 140,
      cornerRadius: 22,
      tint: '#f59e0b',
      tintOpacity: 0.18,
      highlight: 0.9,
    },
  },
  {
    id: 'sunset-glow',
    name: '落日辉光',
    desc: '橙金落日，暖光溢出',
    swatch: 'linear-gradient(135deg,#fdba74,#f97316,#c2410c)',
    category: '光影',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 30,
      height: 48,
      dispersion: 0.55,
      blur: 2,
      saturation: 150,
      cornerRadius: 24,
      tint: '#f97316',
      tintOpacity: 0.16,
      highlight: 1,
      glow: 'rgba(249,115,22,0.35)',
      lightAngle: 315,
    },
  },
  {
    id: 'hologram',
    name: '全息幻彩',
    desc: '极光幻彩，强色散',
    swatch: 'conic-gradient(from 90deg,#c084fc,#22d3ee,#4ade80,#fde047,#c084fc)',
    category: '光影',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 48,
      height: 66,
      dispersion: 1,
      blur: 0,
      saturation: 200,
      cornerRadius: 20,
      highlight: 1,
      glow: 'rgba(167,139,250,0.3)',
      lightAngle: 270,
    },
  },
  {
    id: 'lens-depth',
    name: '景深透镜',
    desc: '边缘高斯弥散，中心清晰',
    swatch: 'radial-gradient(circle at 50% 50%,#f8fafc 30%,#94a3b8 70%,#475569)',
    category: '光影',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 34,
      height: 50,
      dispersion: 0.5,
      blur: 2,
      saturation: 145,
      cornerRadius: 24,
      highlight: 0.9,
      edgeBlur: 0.65,
      vignette: 0.2,
    },
  },
  {
    id: 'spectral-cross',
    name: '四极棱镜',
    desc: '对角色散十字，轴线纯净',
    swatch: 'conic-gradient(from 45deg,#f87171,#fde047,#4ade80,#22d3ee,#818cf8,#f87171)',
    category: '光影',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 48,
      height: 66,
      dispersion: 1,
      blur: 0,
      saturation: 190,
      cornerRadius: 22,
      highlight: 1,
      lightAngle: 315,
    },
  },
  {
    id: 'moonstone',
    name: '月长石',
    desc: '月晕冷辉，乳白流光',
    swatch: 'radial-gradient(circle at 35% 35%,#f8fafc,#c7d2fe 55%,#a5b4fc)',
    category: '光影',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 30,
      height: 46,
      dispersion: 0.55,
      blur: 6,
      saturation: 125,
      cornerRadius: 28,
      tint: '#e0e7ff',
      tintOpacity: 0.16,
      highlight: 0.9,
      glow: 'rgba(191,219,254,0.32)',
      lightAngle: 135,
    },
  },
  {
    id: 'rose-dawn',
    name: '玫瑰晨光',
    desc: '粉金高光，破晓柔光',
    swatch: 'linear-gradient(135deg,#ffe4e6,#fda4af,#e11d48)',
    category: '光影',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 28,
      height: 44,
      dispersion: 0.45,
      blur: 4,
      saturation: 135,
      cornerRadius: 26,
      tint: '#fdf2f8',
      tintOpacity: 0.12,
      highlight: 1,
      highlightColor: '#fda4af',
      lightAngle: 45,
    },
  },

  // ------------------------------ 创意 ------------------------------
  {
    id: 'neon',
    name: '霓虹辉光',
    desc: '赛博朋克霓虹边框',
    swatch: 'linear-gradient(135deg,#f0f,#f0f,#0ff)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 32,
      height: 50,
      dispersion: 0.7,
      blur: 4,
      saturation: 180,
      cornerRadius: 28,
      tint: '#e879f9',
      tintOpacity: 0.12,
      highlight: 1,
      glow: 'rgba(232,121,249,0.35)',
    },
  },
  {
    id: 'cloud',
    name: '云雾玻璃',
    desc: '奶白云雾，柔和轻盈',
    swatch: 'linear-gradient(135deg,#fdf2f8,#fce7f3,#fbcfe8)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 10,
      height: 24,
      dispersion: 0.12,
      blur: 22,
      saturation: 110,
      cornerRadius: 30,
      tint: '#fdf2f8',
      tintOpacity: 0.3,
      highlight: 0.65,
    },
  },
  {
    id: 'dewdrop',
    name: '水滴透镜',
    desc: '胶囊水珠，极限折射',
    swatch: 'radial-gradient(circle at 30% 30%,#e0f2fe,#7dd3fc,#0369a1)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 60,
      height: 80,
      dispersion: 0.9,
      blur: 0,
      saturation: 160,
      cornerRadius: 999,
      highlight: 1,
    },
  },
  {
    id: 'polarized',
    name: '偏振墨镜',
    desc: '深色偏振，冷静克制',
    swatch: 'linear-gradient(135deg,#1c1917,#292524,#0c0a09)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 40,
      height: 60,
      dispersion: 0.35,
      blur: 4,
      saturation: 60,
      cornerRadius: 20,
      tint: '#000000',
      tintOpacity: 0.5,
      highlight: 0.3,
      lightAngle: 180,
    },
  },
  {
    id: 'cola',
    name: '可乐气泡',
    desc: '焦糖气泡，复古汽水',
    swatch: 'linear-gradient(135deg,#78350f,#b45309,#f59e0b)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 26,
      height: 42,
      dispersion: 0.45,
      blur: 3,
      saturation: 145,
      cornerRadius: 26,
      tint: '#78350f',
      tintOpacity: 0.24,
      highlight: 0.9,
      glow: 'rgba(245,158,11,0.25)',
      lightAngle: 135,
    },
  },
  {
    id: 'bubblegum',
    name: '泡泡糖',
    desc: '粉嫩甜心，软萌高光',
    swatch: 'linear-gradient(135deg,#fbcfe8,#f9a8d4,#ec4899)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 18,
      height: 34,
      dispersion: 0.3,
      blur: 8,
      saturation: 130,
      cornerRadius: 34,
      tint: '#f9a8d4',
      tintOpacity: 0.3,
      highlight: 0.85,
      lightAngle: 315,
    },
  },
  {
    id: 'toxic',
    name: '荧光辐射',
    desc: '酸性荧光，警示吸睛',
    swatch: 'linear-gradient(135deg,#bef264,#a3e635,#4d7c0f)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 36,
      height: 54,
      dispersion: 0.75,
      blur: 1,
      saturation: 190,
      cornerRadius: 22,
      tint: '#a3e635',
      tintOpacity: 0.2,
      highlight: 1,
      glow: 'rgba(163,230,53,0.35)',
      lightAngle: 90,
    },
  },
  {
    id: 'mercury',
    name: '水银液滴',
    desc: '铬镜质感，深空形变',
    swatch: 'radial-gradient(circle at 32% 30%,#f1f5f9,#94a3b8 55%,#334155)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 52,
      height: 70,
      dispersion: 0.3,
      blur: 3,
      saturation: 65,
      cornerRadius: 44,
      depthEffect: true,
      tint: '#cbd5e1',
      tintOpacity: 0.3,
      highlight: 1,
      overLight: true,
      lightAngle: 225,
    },
  },
  {
    id: 'mint-candy',
    name: '薄荷硬糖',
    desc: '清凉透亮，甜润边缘',
    swatch: 'linear-gradient(135deg,#d1fae5,#6ee7b7,#10b981)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 40,
      height: 56,
      dispersion: 0.75,
      blur: 2,
      saturation: 175,
      cornerRadius: 34,
      tint: '#6ee7b7',
      tintOpacity: 0.22,
      highlight: 0.95,
      glow: 'rgba(110,231,183,0.3)',
      lightAngle: 250,
    },
  },
  {
    id: 'cyan-flame',
    name: '青焰边缘',
    desc: '电光青边，高色散锐利',
    swatch: 'linear-gradient(135deg,#cffafe,#22d3ee,#0e7490)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 44,
      height: 60,
      dispersion: 0.7,
      blur: 1,
      saturation: 170,
      cornerRadius: 22,
      tint: '#0e7490',
      tintOpacity: 0.16,
      highlight: 1,
      highlightColor: '#22d3ee',
      glow: 'rgba(34,211,238,0.32)',
      lightAngle: 225,
    },
  },

  // ------------------ Phase 9 M2: 质感纹理 ------------------
  {
    id: 'brushed-aluminum',
    name: '拉丝铝板',
    desc: '水平拉丝，金属秩序感',
    swatch: 'linear-gradient(0deg,#e5e7eb,#9ca3af 45%,#d1d5db 55%,#6b7280)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 14,
      height: 26,
      dispersion: 0.12,
      blur: 8,
      saturation: 92,
      cornerRadius: 18,
      tint: '#d1d5db',
      tintOpacity: 0.22,
      highlight: 0.8,
      brushed: 0.75,
      lightAngle: 90,
    },
  },
  {
    id: 'satin-gold',
    name: '缎面拉丝金',
    desc: '缎金拉丝，轻奢线性高光',
    swatch: 'linear-gradient(0deg,#fde68a,#b45309 45%,#fcd34d 55%,#78350f)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 20,
      height: 34,
      dispersion: 0.18,
      blur: 5,
      saturation: 128,
      cornerRadius: 20,
      tint: '#92400e',
      tintOpacity: 0.24,
      highlight: 0.95,
      highlightColor: '#fcd34d',
      brushed: 0.55,
      glow: 'rgba(252,211,77,0.22)',
      glowOpacity: 0.85,
      glowSpread: 32,
      lightAngle: 90,
    },
  },
  {
    id: 'pearl-nacre',
    name: '珍珠母贝',
    desc: '气泡珠光，柔彩干涉',
    swatch: 'radial-gradient(circle at 30% 30%,#fdf4ff,#fbcfe8 45%,#c7d2fe)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 24,
      height: 38,
      dispersion: 0.3,
      blur: 6,
      saturation: 132,
      cornerRadius: 30,
      tint: '#fdf4ff',
      tintOpacity: 0.14,
      highlight: 0.85,
      frost: 0.22,
      bubbles: 0.5,
      lightAngle: 60,
    },
  },
  {
    id: 'abyss-bubbles',
    name: '深海气泡',
    desc: '幽蓝气泡，边缘上浮消散',
    swatch: 'radial-gradient(circle at 40% 30%,#164e63,#0c4a6e 55%,#082f49)',
    category: '材质',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 26,
      height: 44,
      dispersion: 0.25,
      blur: 7,
      saturation: 125,
      cornerRadius: 26,
      tint: '#0c4a6e',
      tintOpacity: 0.32,
      highlight: 0.7,
      bubbles: 0.42,
      edgeBlur: 0.45,
      vignette: 0.38,
      lightAngle: 200,
    },
  },
  {
    id: 'champagne',
    name: '香槟气泡',
    desc: '金气泡升腾，庆祝微醺',
    swatch: 'radial-gradient(circle at 35% 25%,#fef3c7,#fde68a 50%,#d97706)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 22,
      height: 36,
      dispersion: 0.28,
      blur: 4,
      saturation: 138,
      cornerRadius: 999,
      tint: '#fde68a',
      tintOpacity: 0.2,
      highlight: 0.95,
      highlightColor: '#fef3c7',
      bubbles: 0.85,
      glow: 'rgba(253,230,138,0.3)',
      glowSpread: 28,
      lightAngle: 45,
    },
  },
  {
    id: 'soda-pop',
    name: '碳酸汽水',
    desc: '青柠气泡，锐利清冽',
    swatch: 'radial-gradient(circle at 30% 30%,#ecfeff,#a5f3fc 55%,#0891b2)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 38,
      height: 54,
      dispersion: 0.6,
      blur: 2,
      saturation: 160,
      cornerRadius: 24,
      tint: '#06b6d4',
      tintOpacity: 0.16,
      highlight: 1,
      bubbles: 0.62,
      glow: 'rgba(103,232,249,0.28)',
      lightAngle: 315,
    },
  },
  // ---------------------- Phase 10 M3: motion presets ----------------------
  {
    id: 'deep-surge',
    name: '深海涌动',
    desc: '气泡上浮，幽蓝呼吸',
    swatch: 'radial-gradient(circle at 30% 20%,#164e63,#0e7490 60%,#083344)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 24,
      height: 40,
      dispersion: 0.22,
      blur: 6,
      saturation: 118,
      cornerRadius: 28,
      tint: '#0c4a6e',
      tintOpacity: 0.3,
      highlight: 0.75,
      lightAngle: 200,
      bubbles: 0.5,
      bubbleSize: 0.8,
      bubbleDensity: 1.5,
      bubbleRise: 0.55,
      glow: 'rgba(56,189,248,0.35)',
      glowSpread: 30,
      glowPulse: 0.45,
      vignette: 0.4,
    },
  },
  {
    id: 'moon-breath',
    name: '呼吸月光',
    desc: '柔白辉光，静谧起伏',
    swatch: 'radial-gradient(circle at 50% 30%,#f8fafc,#cbd5e1 55%,#64748b)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 18,
      height: 30,
      dispersion: 0.12,
      blur: 8,
      saturation: 105,
      cornerRadius: 32,
      tint: '#e2e8f0',
      tintOpacity: 0.14,
      highlight: 0.9,
      lightAngle: 315,
      glow: 'rgba(226,232,240,0.4)',
      glowSpread: 46,
      glowOpacity: 0.9,
      glowPulse: 0.35,
      frost: 0.22,
    },
  },
  {
    id: 'aurora-flow',
    name: '流光溢彩',
    desc: '高光环游，极光流转',
    swatch: 'conic-gradient(from 0deg,#5eead4,#818cf8,#f472b6,#5eead4)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 30,
      height: 46,
      dispersion: 0.7,
      blur: 3,
      saturation: 150,
      cornerRadius: 26,
      tint: '#312e81',
      tintOpacity: 0.12,
      highlight: 1,
      highlightColor: '#5eead4',
      lightAngle: 45,
      rimFlow: 0.6,
      glow: 'rgba(94,234,212,0.3)',
      glowSpread: 26,
      vignette: 0.2,
    },
  },
  {
    id: 'lava-surge',
    name: '熔岩暗涌',
    desc: '暖红脉动，地心引力',
    swatch: 'radial-gradient(circle at 40% 25%,#fdba74,#ea580c 55%,#431407)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 26,
      height: 44,
      dispersion: 0.18,
      blur: 5,
      saturation: 128,
      cornerRadius: 20,
      tint: '#431407',
      tintOpacity: 0.34,
      highlight: 0.8,
      highlightColor: '#fdba74',
      lightAngle: 160,
      bubbles: 0.4,
      bubbleSize: 1.4,
      bubbleDensity: 0.7,
      bubbleRise: 0.3,
      glow: 'rgba(234,88,12,0.45)',
      glowSpread: 36,
      glowPulse: 0.6,
      vignette: 0.45,
    },
  },
  {
    id: 'stardust-drift',
    name: '星尘漂浮',
    desc: '微尘上浮，星际薄雾',
    swatch: 'radial-gradient(circle at 35% 30%,#e0e7ff,#a5b4fc 50%,#1e1b4b)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 20,
      height: 34,
      dispersion: 0.3,
      blur: 4,
      saturation: 132,
      cornerRadius: 999,
      tint: '#312e81',
      tintOpacity: 0.18,
      highlight: 0.85,
      lightAngle: 300,
      frost: 0.3,
      bubbles: 0.55,
      bubbleSize: 0.45,
      bubbleDensity: 2.2,
      bubbleRise: 0.25,
      glow: 'rgba(165,180,252,0.32)',
      glowSpread: 32,
      vignette: 0.3,
    },
  },
  {
    id: 'gold-thread',
    name: '曳光金丝',
    desc: '斜向拉丝，流光巡游',
    swatch: 'linear-gradient(60deg,#fef3c7,#f59e0b 45%,#78350f)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 28,
      height: 42,
      dispersion: 0.32,
      blur: 3,
      saturation: 142,
      cornerRadius: 22,
      tint: '#78350f',
      tintOpacity: 0.18,
      highlight: 0.95,
      highlightColor: '#fbbf24',
      lightAngle: 315,
      brushed: 0.42,
      brushedAngle: 60,
      rimFlow: 0.5,
      glow: 'rgba(251,191,36,0.3)',
      glowSpread: 26,
      vignette: 0.25,
    },
  },
  // ---------------- Phase 11: directional-shadow showcase ----------------
  {
    id: 'morning-float',
    name: '晨光悬浮',
    desc: '清晨光从右上来，卡片浮起',
    swatch: 'linear-gradient(200deg,#fff7ed,#fed7aa 55%,#f97316)',
    category: '经典',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 26,
      height: 40,
      dispersion: 0.3,
      blur: 3,
      saturation: 125,
      cornerRadius: 24,
      tint: '#ffedd5',
      tintOpacity: 0.1,
      highlight: 0.9,
      highlightColor: '#fff7ed',
      lightAngle: 30,
      shadowIntensity: 0.55,
      shadowDistance: 20,
      shadowSoftness: 34,
      glow: 'rgba(255,237,213,0.18)',
      glowSpread: 18,
    },
  },
  {
    id: 'dusk-silhouette',
    name: '暮色剪影',
    desc: '低角度逆光，长影拖曳',
    swatch: 'linear-gradient(340deg,#1e1b4b,#c2410c 62%,#fdba74)',
    category: '光影',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 30,
      height: 46,
      dispersion: 0.42,
      blur: 6,
      saturation: 135,
      cornerRadius: 18,
      tint: '#312e81',
      tintOpacity: 0.26,
      highlight: 0.95,
      highlightColor: '#fdba74',
      lightAngle: 285,
      shadowIntensity: 0.7,
      shadowDistance: 32,
      shadowSoftness: 46,
      vignette: 0.32,
    },
  },
  {
    id: 'levitating-isle',
    name: '悬浮岛',
    desc: '顶光直射，深影沉底',
    swatch: 'radial-gradient(circle at 50% 18%,#e0f2fe,#38bdf8 55%,#0c4a6e)',
    category: '创意',
    config: {
      ...DEFAULT_CONFIG,
      refraction: 32,
      height: 48,
      dispersion: 0.4,
      blur: 4,
      saturation: 138,
      cornerRadius: 28,
      tint: '#0c4a6e',
      tintOpacity: 0.2,
      highlight: 1,
      lightAngle: 0,
      shadowIntensity: 0.6,
      shadowDistance: 26,
      shadowSoftness: 40,
      bubbles: 0.3,
      bubbleSize: 0.7,
      bubbleDensity: 0.8,
      glow: 'rgba(125,211,252,0.25)',
      glowSpread: 30,
      vignette: 0.22,
    },
  },
]
